"""
Comprehensive ES-DE system definitions.
Each entry maps to a system supported by ES-DE with its folder name and ROM extensions.
"""

SYSTEMS_REGISTRY = [
    # ── Nintendo ──────────────────────────────────────────────────────────────
    {
        "name": "Nintendo Entertainment System",
        "esde_folder": "nes",
        "extensions": ".nes,.unf,.unif",
        "manufacturer": "Nintendo",
        "release_year": 1983,
        "screenscraper_id": 3,
        "thegamesdb_id": 7,
    },
    {
        "name": "Super Nintendo Entertainment System",
        "esde_folder": "snes",
        "extensions": ".sfc,.smc,.snes,.bs,.fig,.swc",
        "manufacturer": "Nintendo",
        "release_year": 1990,
        "screenscraper_id": 4,
        "thegamesdb_id": 6,
    },
    {
        "name": "Nintendo 64",
        "esde_folder": "n64",
        "extensions": ".n64,.v64,.z64",
        "manufacturer": "Nintendo",
        "release_year": 1996,
        "screenscraper_id": 14,
        "thegamesdb_id": 3,
    },
    {
        "name": "Game Boy",
        "esde_folder": "gb",
        "extensions": ".gb",
        "manufacturer": "Nintendo",
        "release_year": 1989,
        "screenscraper_id": 9,
        "thegamesdb_id": 4,
    },
    {
        "name": "Game Boy Color",
        "esde_folder": "gbc",
        "extensions": ".gbc",
        "manufacturer": "Nintendo",
        "release_year": 1998,
        "screenscraper_id": 10,
        "thegamesdb_id": 41,
    },
    {
        "name": "Game Boy Advance",
        "esde_folder": "gba",
        "extensions": ".gba",
        "manufacturer": "Nintendo",
        "release_year": 2001,
        "screenscraper_id": 12,
        "thegamesdb_id": 5,
    },
    {
        "name": "Nintendo DS",
        "esde_folder": "nds",
        "extensions": ".nds",
        "manufacturer": "Nintendo",
        "release_year": 2004,
        "screenscraper_id": 15,
        "thegamesdb_id": 8,
    },
    {
        "name": "Nintendo 3DS",
        "esde_folder": "3ds",
        "extensions": ".3ds,.3dsx,.cia,.cxi,.app",
        "manufacturer": "Nintendo",
        "release_year": 2011,
        "screenscraper_id": 17,
        "thegamesdb_id": 4912,
    },
    {
        "name": "Nintendo Switch",
        "esde_folder": "switch",
        "extensions": ".nsp,.xci,.nca,.nso,.nro",
        "manufacturer": "Nintendo",
        "release_year": 2017,
        "screenscraper_id": 225,
        "thegamesdb_id": 4971,
    },
    {
        "name": "GameCube",
        "esde_folder": "gc",
        "extensions": ".gcm,.iso,.gcz,.chd,.rvz,.wia",
        "manufacturer": "Nintendo",
        "release_year": 2001,
        "screenscraper_id": 13,
        "thegamesdb_id": 2,
    },
    {
        "name": "Wii",
        "esde_folder": "wii",
        "extensions": ".iso,.wbfs,.gcz,.chd,.rvz,.wia,.wad",
        "manufacturer": "Nintendo",
        "release_year": 2006,
        "screenscraper_id": 16,
        "thegamesdb_id": 9,
    },
    {
        "name": "Wii U",
        "esde_folder": "wiiu",
        "extensions": ".wud,.wux,.iso,.rpx",
        "manufacturer": "Nintendo",
        "release_year": 2012,
        "screenscraper_id": 18,
        "thegamesdb_id": 38,
    },
    {
        "name": "Virtual Boy",
        "esde_folder": "virtualboy",
        "extensions": ".vb,.vboy",
        "manufacturer": "Nintendo",
        "release_year": 1995,
        "screenscraper_id": 11,
        "thegamesdb_id": 4918,
    },
    # ── Sony ──────────────────────────────────────────────────────────────────
    {
        "name": "PlayStation",
        "esde_folder": "psx",
        "extensions": ".bin,.cue,.img,.iso,.pbp,.chd,.ecm,.mdf,.toc,.cbn,.m3u",
        "manufacturer": "Sony",
        "release_year": 1994,
        "screenscraper_id": 57,
        "thegamesdb_id": 10,
    },
    {
        "name": "PlayStation 2",
        "esde_folder": "ps2",
        "extensions": ".iso,.img,.bin,.chd,.cso,.gz",
        "manufacturer": "Sony",
        "release_year": 2000,
        "screenscraper_id": 58,
        "thegamesdb_id": 11,
    },
    {
        "name": "PlayStation 3",
        "esde_folder": "ps3",
        "extensions": ".iso,.pkg,.chd",
        "manufacturer": "Sony",
        "release_year": 2006,
        "screenscraper_id": 59,
        "thegamesdb_id": 12,
    },
    {
        "name": "PlayStation Portable",
        "esde_folder": "psp",
        "extensions": ".iso,.cso,.pbp,.elf,.prx,.chd",
        "manufacturer": "Sony",
        "release_year": 2004,
        "screenscraper_id": 61,
        "thegamesdb_id": 13,
    },
    {
        "name": "PlayStation Vita",
        "esde_folder": "psvita",
        "extensions": ".vpk,.chd",
        "manufacturer": "Sony",
        "release_year": 2011,
        "screenscraper_id": 62,
        "thegamesdb_id": 39,
    },
    # ── Sega ──────────────────────────────────────────────────────────────────
    {
        "name": "Sega Master System",
        "esde_folder": "mastersystem",
        "extensions": ".sms,.bin",
        "manufacturer": "Sega",
        "release_year": 1985,
        "screenscraper_id": 2,
        "thegamesdb_id": 35,
    },
    {
        "name": "Sega Mega Drive / Genesis",
        "esde_folder": "megadrive",
        "extensions": ".md,.smd,.gen,.bin,.68k,.sgd",
        "manufacturer": "Sega",
        "release_year": 1988,
        "screenscraper_id": 1,
        "thegamesdb_id": 36,
    },
    {
        "name": "Sega CD",
        "esde_folder": "segacd",
        "extensions": ".bin,.cue,.iso,.chd",
        "manufacturer": "Sega",
        "release_year": 1991,
        "screenscraper_id": 20,
        "thegamesdb_id": 21,
    },
    {
        "name": "Sega 32X",
        "esde_folder": "sega32x",
        "extensions": ".32x,.bin",
        "manufacturer": "Sega",
        "release_year": 1994,
        "screenscraper_id": 19,
        "thegamesdb_id": 33,
    },
    {
        "name": "Sega Saturn",
        "esde_folder": "saturn",
        "extensions": ".bin,.cue,.iso,.chd,.mdf,.toc,.ccd",
        "manufacturer": "Sega",
        "release_year": 1994,
        "screenscraper_id": 22,
        "thegamesdb_id": 17,
    },
    {
        "name": "Sega Dreamcast",
        "esde_folder": "dreamcast",
        "extensions": ".chd,.gdi,.iso,.cdi,.cue,.bin",
        "manufacturer": "Sega",
        "release_year": 1998,
        "screenscraper_id": 23,
        "thegamesdb_id": 16,
    },
    {
        "name": "Game Gear",
        "esde_folder": "gamegear",
        "extensions": ".gg",
        "manufacturer": "Sega",
        "release_year": 1990,
        "screenscraper_id": 21,
        "thegamesdb_id": 20,
    },
    # ── Arcade (Where the ZIP / 7z container IS the driver ROM set) ───────────
    {
        "name": "MAME",
        "esde_folder": "mame",
        "extensions": ".zip,.7z,.chd",
        "manufacturer": "Various",
        "release_year": None,
        "screenscraper_id": 75,
        "thegamesdb_id": 23,
    },
    {
        "name": "Arcade",
        "esde_folder": "arcade",
        "extensions": ".zip,.7z",
        "manufacturer": "Various",
        "release_year": None,
        "screenscraper_id": 75,
        "thegamesdb_id": 23,
    },
    {
        "name": "FinalBurn Neo",
        "esde_folder": "fbneo",
        "extensions": ".zip,.7z",
        "manufacturer": "Various",
        "release_year": None,
        "screenscraper_id": 75,
        "thegamesdb_id": 23,
    },
    {
        "name": "Neo Geo",
        "esde_folder": "neogeo",
        "extensions": ".zip,.7z",
        "manufacturer": "SNK",
        "release_year": 1990,
        "screenscraper_id": 142,
        "thegamesdb_id": 24,
    },
    # ── Atari ─────────────────────────────────────────────────────────────────
    {
        "name": "Atari 2600",
        "esde_folder": "atari2600",
        "extensions": ".a26,.bin",
        "manufacturer": "Atari",
        "release_year": 1977,
        "screenscraper_id": 26,
        "thegamesdb_id": 22,
    },
    {
        "name": "Atari 5200",
        "esde_folder": "atari5200",
        "extensions": ".a52,.bin,.car",
        "manufacturer": "Atari",
        "release_year": 1982,
        "screenscraper_id": 40,
        "thegamesdb_id": 26,
    },
    {
        "name": "Atari 7800",
        "esde_folder": "atari7800",
        "extensions": ".a78,.bin",
        "manufacturer": "Atari",
        "release_year": 1986,
        "screenscraper_id": 41,
        "thegamesdb_id": 27,
    },
    {
        "name": "Atari Lynx",
        "esde_folder": "atarilynx",
        "extensions": ".lnx,.o",
        "manufacturer": "Atari",
        "release_year": 1989,
        "screenscraper_id": 28,
        "thegamesdb_id": 4924,
    },
    {
        "name": "Atari Jaguar",
        "esde_folder": "atarijaguar",
        "extensions": ".j64,.jag",
        "manufacturer": "Atari",
        "release_year": 1993,
        "screenscraper_id": 27,
        "thegamesdb_id": 28,
    },
    # ── Microsoft ─────────────────────────────────────────────────────────────
    {
        "name": "Xbox",
        "esde_folder": "xbox",
        "extensions": ".iso,.xbe",
        "manufacturer": "Microsoft",
        "release_year": 2001,
        "screenscraper_id": 32,
        "thegamesdb_id": 14,
    },
    {
        "name": "Xbox 360",
        "esde_folder": "xbox360",
        "extensions": ".iso,.xex,.god",
        "manufacturer": "Microsoft",
        "release_year": 2005,
        "screenscraper_id": 33,
        "thegamesdb_id": 15,
    },
    # ── NEC / PC Engine ───────────────────────────────────────────────────────
    {
        "name": "PC Engine / TurboGrafx-16",
        "esde_folder": "pcengine",
        "extensions": ".pce,.bin",
        "manufacturer": "NEC",
        "release_year": 1987,
        "screenscraper_id": 31,
        "thegamesdb_id": 34,
    },
    {
        "name": "PC Engine CD",
        "esde_folder": "pcenginecd",
        "extensions": ".bin,.cue,.iso,.chd",
        "manufacturer": "NEC",
        "release_year": 1988,
        "screenscraper_id": 114,
        "thegamesdb_id": 4955,
    },
    # ── SNK Handhelds ─────────────────────────────────────────────────────────
    {
        "name": "Neo Geo Pocket",
        "esde_folder": "ngp",
        "extensions": ".ngp,.ngc",
        "manufacturer": "SNK",
        "release_year": 1998,
        "screenscraper_id": 25,
        "thegamesdb_id": 4922,
    },
    {
        "name": "Neo Geo Pocket Color",
        "esde_folder": "ngpc",
        "extensions": ".ngc,.ngp",
        "manufacturer": "SNK",
        "release_year": 1999,
        "screenscraper_id": 82,
        "thegamesdb_id": 4923,
    },
    # ── Bandai ────────────────────────────────────────────────────────────────
    {
        "name": "WonderSwan",
        "esde_folder": "wonderswan",
        "extensions": ".ws",
        "manufacturer": "Bandai",
        "release_year": 1999,
        "screenscraper_id": 45,
        "thegamesdb_id": 4925,
    },
    {
        "name": "WonderSwan Color",
        "esde_folder": "wonderswancolor",
        "extensions": ".wsc,.ws",
        "manufacturer": "Bandai",
        "release_year": 2000,
        "screenscraper_id": 46,
        "thegamesdb_id": 4926,
    },
    # ── Misc ──────────────────────────────────────────────────────────────────
    {
        "name": "DOS",
        "esde_folder": "dos",
        "extensions": ".bat,.com,.exe",
        "manufacturer": "Microsoft",
        "release_year": None,
        "screenscraper_id": 135,
        "thegamesdb_id": 1,
    },
    {
        "name": "ScummVM",
        "esde_folder": "scummvm",
        "extensions": ".scummvm",
        "manufacturer": "Various",
        "release_year": None,
        "screenscraper_id": 123,
        "thegamesdb_id": None,
    },
]

# Build a lookup dict: extension -> list of esde_folder names
EXTENSION_TO_SYSTEMS: dict[str, list[str]] = {}
for _sys in SYSTEMS_REGISTRY:
    for _ext in _sys["extensions"].split(","):
        _ext = _ext.strip().lower()
        EXTENSION_TO_SYSTEMS.setdefault(_ext, []).append(_sys["esde_folder"])
